name: Hello World
author: Ali Alaa
description: "Greet someone and record the time"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "node16"
  pre: "setup.js"
  pre-if: runner.os == 'linux'
  main: "index.js"
  post: "cleanup.js"
  post-if: runner.os == 'linux'
