name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      username:
        description: "A username passed from the caller workflow"
        default: "john-doe"
        required: false
        type: string

jobs:
  call-workflow-passing-data:
    uses: alialaaorg/workflows/.github/workflows/reusable.yaml@main
    with:
      username: ${{ inputs.username }}
    secrets:
      access-token: ${{ secrets.access-token }}
