name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      username:
        description: "A username passed from the caller workflow"
        default: "john-doe"
        required: false
        type: string

jobs:
  call-workflow-in-another-repo:
    uses: alialaaorg/workflows/.github/workflows/reusable.yaml@main
    with:
      username: ${{ inputs.username }}
    secrets:
      access-token: ${{ secrets.access-token }}
  call-workflow-on-same-repo:
    uses: ./.github/workflows/reusable-workflow.yaml
    secrets: inherit
  use-reusable-job-outputs:
    runs-on: ubuntu-latest
    needs: call-workflow-on-same-repo
    steps:
      - run: echo ${{ needs.call-workflow-on-same-repo.outputs.date }}
