name: Using Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
      ports:
        - 80
      # volumes:
      # - vol_name:/path/in/container
      #   - /path/in/container
      # - /path/in/host:/path/in/container
      # options: --cpus 1
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL
      - name: Create File
        run: echo 'Some text' > text.txt
      - name: Container in a Step
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3
      - name: Log Node Version
        uses: docker://node:18.16-alpine3.17
        with:
          args: -v
      - name: Show file contents
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: cat
          args: text.txt
      - uses: actions/checkout@v3
      - name: Run bash script
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: ./script.sh
          args: "Some string"
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: random
          SLACK_TITLE: From Github Actions
          SLACK_MESSAGE: ${{github.actor}} ${{github.event_name}}
          SLACK_COLOR: "#f03"
          SLACK_USERNAME: Github Actions
