name: Matrix
on: [push]
#------- ORIGINAL --------#
# {os: windows-latest, node-version: 14}
# {os: windows-latest, node-version: 15}
# {os: windows-latest, node-version: 16}
# {os: ubuntu-latest, node-version: 14}
# {os: ubuntu-latest, node-version: 15}
# {os: ubuntu-latest, node-version: 16}

#------- After include/exclude --------#
# {os: windows-latest, node-version: 14, experimental: false}
# {os: windows-latest, node-version: 15, experimental: false}
# {os: windows-latest, node-version: 16, experimental: false}
# X {os: ubuntu-latest, node-version: 14, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 15, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
# {os: macos-latest, node-version: 15, experimental: false}

jobs:
  node-matrix:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [14, 15, 16]
        include:
          - os: macos-latest
            node-version: 15
          - os: ubuntu-latest
            is-ubuntu: true
          - experimental: false
          - os: ubuntu-latest
            node-version: 16
            experimental: true
        exclude:
          - os: ubuntu-latest
            node-version: 14
      # max-parallel: 3
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo '${{ toJson(matrix) }}'
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
