name: Matrix
on: [push]

jobs:
  node-matrix:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [14, 15, 16]
      max-parallel: 3
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
