name: Reusable Workflow
on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      date:
        description: "date output"
        value: ${{ jobs.generate-output.outputs.date }}

jobs:
  nested-workflow-call:
    uses: alialaaorg/workflows/.github/workflows/reusable.yaml@main
    with:
      username: "Ali"
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  generate-output:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      date: ${{ steps.date-step.outputs.date }}
    steps:
      - run: echo "date=$(date)" >> $GITHUB_OUTPUT
        id: date-step
