name: "Close stale issues and pull requests"
on:
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0 15 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: "This is some message."
          days-before-stale: 1
          days-before-close: 5
